name: dkzippa_dart_date
description: Date manipulation library. DateTime extensions. Also includes an Interval object.
version: 1.3.3
homepage: https://github.com/dkzippa/dart_date

environment:
  sdk: ">=3.2.0 <4.0.0"


dependencies:
  intl: ^0.19.0
  timeago: ^3.6.1
dev_dependencies:
  test: ^1.25.5
